---
title: "BikeShareAnalysis"
author: "Razeen"
date: "2024-03-14"
output: rmarkdown::github_document
---


### Load Packages
```{r}
library(tidyverse)
library(readr)
```


Reading CSV files into dataframes
```{r readCSV}
Data202303 <- read_csv('csv_files/202303-divvy-tripdata.csv')
Data202304 <- read_csv('csv_files/202304-divvy-tripdata.csv')
Data202305 <- read_csv('csv_files/202305-divvy-tripdata.csv')
Data202306 <- read_csv('csv_files/202306-divvy-tripdata.csv')
Data202307 <- read_csv('csv_files/202307-divvy-tripdata.csv')
Data202308 <- read_csv('csv_files/202308-divvy-tripdata.csv')
Data202309 <- read_csv('csv_files/202309-divvy-tripdata.csv')
Data202310 <- read_csv('csv_files/202310-divvy-tripdata.csv')
Data202311 <- read_csv('csv_files/202311-divvy-tripdata.csv')
Data202312 <- read_csv('csv_files/202312-divvy-tripdata.csv')
Data202401 <- read_csv('csv_files/202401-divvy-tripdata.csv')
Data202402 <- read_csv('csv_files/202402-divvy-tripdata.csv')

```

Check for columns consistency 
```{r}
str(Data202303)
str(Data202304)
str(Data202305)
str(Data202306)
str(Data202307)
str(Data202308)
str(Data202309)
str(Data202310)
str(Data202311)
str(Data202312)
str(Data202401)
str(Data202402)
```

Since all columns in dataframes are identical, all dataframes can be used to merge together to form a single dataframe.
```{r}
MergedData <- rbind(Data202303, Data202304, Data202305,
                         Data202306, Data202307, Data202308,
                         Data202309, Data202310, Data202311,
                         Data202312, Data202401, Data202402)
```


Check the new dataframe created
```{r}
head(MergedData)
```







